# Generated by Django 2.0.1 on 2018-01-04 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='添加方式名称')),
            ],
            options={
                'verbose_name_plural': '添加方式类型',
                'db_table': 'add_way',
                'verbose_name': '添加方式类型',
            },
        ),
        migrations.CreateModel(
            name='cloud_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100, verbose_name='API_ID')),
                ('api_secrect', models.CharField(max_length=100, verbose_name='API_SECRECT')),
                ('user', models.ForeignKey(on_delete='PROTECT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'API信息',
                'db_table': 'api',
                'verbose_name': 'API信息',
            },
        ),
        migrations.CreateModel(
            name='ip_or_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_way_id', models.ForeignKey(on_delete='PROTECT', to='user.add_way', verbose_name='添加方式ID')),
            ],
            options={
                'verbose_name_plural': '添加方式',
                'db_table': 'ip_or_api',
                'verbose_name': '添加方式',
            },
        ),
        migrations.CreateModel(
            name='mc_inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': 'MC信息',
                'db_table': 'mc_inf',
                'verbose_name': 'MC信息',
            },
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('secrect', models.CharField(max_length=100, verbose_name='密钥')),
                ('java', models.BooleanField(default=False, verbose_name='Java是否安装')),
                ('java_version', models.CharField(blank=True, max_length=30, verbose_name='Java版本')),
                ('user_id', models.ForeignKey(on_delete='PROTECT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '服务器信息',
                'db_table': 'server',
                'verbose_name': '服务器信息',
            },
        ),
        migrations.CreateModel(
            name='server_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.ForeignKey(on_delete='PROTECT', to='user.cloud_api', verbose_name='api')),
                ('server_id', models.ForeignKey(on_delete='PROTECT', to='user.server', verbose_name='sever')),
            ],
            options={
                'verbose_name_plural': '通过API添加服务器',
                'db_table': 'server_api',
                'verbose_name': '通过API添加服务器',
            },
        ),
        migrations.AddField(
            model_name='mc_inf',
            name='server_id',
            field=models.ForeignKey(on_delete='PROTECT', to='user.server', verbose_name='所属服务器'),
        ),
        migrations.AddField(
            model_name='ip_or_api',
            name='server_id',
            field=models.ForeignKey(on_delete='PROTECT', to='user.server', verbose_name='服务器'),
        ),
    ]
