# Generated by Django 2.0.1 on 2018-01-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='user_id',
            new_name='user',
        ),
    ]
