# Generated by Django 2.0.1 on 2018-01-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180104_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mc_inf',
            old_name='server_id',
            new_name='server',
        ),
    ]
