# Generated by Django 2.0.1 on 2018-01-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180106_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server_api',
            old_name='api_id',
            new_name='api',
        ),
        migrations.RenameField(
            model_name='server_api',
            old_name='server_id',
            new_name='server',
        ),
    ]
